# Generated by Django 3.2.12 on 2022-02-28 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('brand', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('manufactured', models.DateTimeField()),
            ],
        ),
    ]
