# Generated by Django 3.2.12 on 2022-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.DateField(),
        ),
    ]
